apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: team-{{ .Values.teamName }}
  labels:
    app: {{ .Values.service.name }}
    team: {{ .Values.teamName }}
spec:
  selector:
    app: {{ .Values.service.name }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
  type: {{ .Values.service.type }}
