x-service-defaults: &service-defaults
  restart: unless-stopped
  networks:
    - app-network

services:

  postgres:
    <<: *service-defaults
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: market_trends_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  market-trends:
    <<: *service-defaults
    image: market-trends/market-trends:latest
    build:
      context: ../market-trends
      dockerfile: Dockerfile
    container_name: market-trends
    ports:
      - "6062:6062"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m # Example JVM settings
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - maildev
      - postgres

  maildev:
    <<: *service-defaults
    image: maildev/maildev
    environment:
      - TZ=Asia/Riyadh
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    volumes:
      - maildev_data:/home/maildev:rw

volumes:
  postgres_db_data:
    driver: local
  maildev_data:
    driver: local

networks:
  app-network:
    driver: bridge
