#spring
spring:
  application:
    name: user-management
  datasource:
    url: jdbc:postgresql://localhost:5432/market_trends_db
    username: user_management_user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: user_management
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: false
        default_schema: user_management



  flyway:
    user: user_management_user
    password: password
    baseline-on-migrate: true
    default-schema: user_management



  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
        starttls:
          enable: true
          required: true
    threads:
      virtual:
        enabled: true


#server
server:
  port: 6061
  servlet:
    context-path: /user-management

security:
  jwt:
    secret:
      hex: 9f3c6e1a4b8d2f7c1e0d5a9c3b7e6f12a4c8d0b2f3e7c6a19d3b5f7e2c1a0d4b
    issuer: user-management
    expiration-minutes: 30






