#spring
spring:
  application:
    name: user-management
  datasource:
    url: jdbc:postgresql://localhost:5432/market_trends_db
    username: user_service
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: false



  flyway:
    user: user_service
    password: password
    baseline-on-migrate: true



  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
        starttls:
          enable: true
          required: true
    threads:
      virtual:
        enabled: true


#server
server:
  port: 6061
  servlet:
    context-path: /user-management




